<div class="lwps_form">

	<h1 class="lwps_headline"><?php echo $this->i18n['confirm_headline']; ?></h1>

    <p class="lwps_infotext"><?php echo $this->i18n['confirm_intro']; ?></p>
    
    <form name="form" id="form" action="<?php echo $this->actionUrl; ?>" method="post" style="margin-bottom:30px;">
        <input type="hidden" name="save" value="1">
        
        <label class="lwps_label"><?php echo $this->i18n['form_contactname']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->data['contactname']; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_country']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->country; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_organisationname']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->data['organisation']; ?></div>

        <label class="lwps_label"><?php echo $this->i18n['form_organisationtype']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->orgatype; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_email']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->data['email']; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_phone']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->data['telephone']; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_keywords']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->data['keywords']; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_topic']; ?>:</label>
        <div class="lwps_confirm"><?php echo $this->topic; ?></div>
        
        <label class="lwps_label"><?php echo $this->i18n['form_description']; ?>:</label>
        <div class="lwps_confirm"><?php echo nl2br($this->data['description']); ?></div>

        <label class="lwps_label"><?php echo $this->i18n['form_orgadesc']; ?>:</label>
        <div class="lwps_confirm"><?php echo nl2br($this->data['orgadesc']); ?></div>
        
        <br/>        
        
        <div id="lwps_confirm_check">
            <?php if(isset($this->errors["isconfirmed"])): ?><p class="lwps_error"><?php echo $this->errors["isconfirmed"]; ?></p><?php endif; ?>
            <input type="checkbox" name="isconfirmed" value="CONFIRMED" />&nbsp;<?php echo $this->i18n['confirm_confirmation']; ?>
        </div>
        
        <div id="lwps_back_or_send_area">
            <input id="lwps_back" type="button" onclick="document.location.href='<?php echo $this->backUrl;?>';" value="<?php echo $this->i18n['confirm_back']; ?>" />&nbsp;
            <input id="lwps_send" type="submit" name="submitbutton" value="<?php echo $this->i18n['confirm_send']; ?>" />
        </div>
        
    </form>

</div>
