<div class="lwps_form">

	<h1 class="lwps_headline"><?php echo $this->i18n['entry_headline']; ?></h1>
    
    <label class="lwps_label"><?php echo $this->i18n['entry_contactname']; ?></label>
    <div class="lwps_value"><?php echo $this->data['contactname']; ?></div>
    
    <label class="lwps_label"><?php echo $this->i18n['entry_country']; ?></label>
    <div class="lwps_value"><?php echo $this->country; ?></div>
    
    <label class="lwps_label"><?php echo $this->i18n['entry_organisation']; ?></label>
    <div class="lwps_value"><?php echo $this->data['organisation']; ?></div>    
    
    <label class="lwps_label"><?php echo $this->i18n['entry_orgatype']; ?></label>
    <div class="lwps_value"><?php echo $this->orgatype; ?></div>
    
    <label class="lwps_label"><?php echo $this->i18n['entry_email']; ?>:</label>
    <div class="lwps_value"><a href="mailto:<?php echo $this->data['email']; ?>"><?php echo $this->data['email']; ?></a></div>
    
    <label class="lwps_label"><?php echo $this->i18n['entry_keywords']; ?></label>
    <div class="lwps_value"><?php echo $this->data['keywords']; ?></div>    
    
    <label class="lwps_label"><?php echo $this->i18n['entry_topic']; ?></label>
    <div class="lwps_value"><?php echo $this->topic; ?></div>    
    
    <label class="lwps_label"><?php echo $this->i18n['entry_description']; ?></label>
    <div class="view_description"><?php echo nl2br($this->data['description']); ?></div>    
 
    <label class="lwps_label"><?php echo $this->i18n['entry_orgadesc']; ?></label>
    <div class="view_description"><?php echo nl2br($this->data['orgadesc']); ?></div>    
  
    <div class="lwps_back_area">
        <a href="<?php echo lw_page::getInstance()->getUrl(); ?>"><?php echo $this->i18n['entry_back']; ?></a>
    </div>

</div>
