<div class="lwps_form">

	<h1 class="lwps_headline"><?php if ($this->SearchOrOffer == "offer"): echo $this->i18n['form_offertitle']; else: echo $this->i18n['form_searchtitle']; endif; ?></h1>

	<?php if($this->isAdmin === true): ?>

    <div class="lwps_adminarea">
        
        <div class="lwps_deletearea">
            <form name="deleteform" action="<?php echo $this->deleteUrl; ?>" method="POST">
                <input type="hidden" name="deleteid" value="<?php echo $this->data['id']; ?>" />
                <p><?php echo $this->i18n['form_deletenotundoable']; ?></p>
                <input class="lwps_button" name="deletebutton" type="submit" value="<?php echo $this->i18n['form_delete']; ?>" onclick="if(!confirm('<?php echo $this->i18n['form_deleteconfirm']; ?>')) return false;"/>
            </form>
        </div>   

        <div class="lwps_publisharea">
		    <?php if ($this->data['published'] < 1): ?>
            <form name="publishform" action="<?php echo $this->publishUrl; ?>" method="POST">
                <input type="hidden" name="publishid" value="<?php echo $this->data['id']; ?>" />
                <p>&nbsp;</p>
                <input class="lwps_button" name="publishbutton" type="submit" value="<?php echo $this->i18n['form_publish']; ?>"/>
            </form>
            <?php else: ?>
            <form name="publishform" action="<?php echo $this->unpublishUrl; ?>" method="POST">
                <input type="hidden" name="publishid" value="<?php echo $this->data['id']; ?>" />
                <p>&nbsp;</p>
                <input class="lwps_button" name="publishbutton" type="submit" value="<?php echo $this->i18n['form_unpublish']; ?>"/>
            </form>
        	<?php endif; ?>    
            
        </div>
        
        <div style="clear:both;">&nbsp;</div>

    </div>

    <?php endif; ?>    
    
    <form name="form" id="form" action="<?php echo $this->actionUrl; ?>" method="post" style="margin-bottom:30px;">
        <input type="hidden" name="save" value="1">
        
        <?php if($this->isAdmin === true): ?>
        	<input type="hidden" name="id" value="<?php echo $this->data['id']; ?>">
        <?php endif; ?>
        
        <?php if(!empty($this->errors)): ?>
        	<div class="lwps_error"><?php echo $this->i18n['form_error']; ?></div>
        <?php endif; ?>  
          
        <label class="lwps_label"><?php echo $this->i18n['form_contactname']; ?></label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_contactname_info']; ?></p>
        <?php if(isset($this->errors["contactname"])): ?><p class="lwps_error"><?php echo $this->errors["contactname"]; ?></p><?php endif; ?>
        <input class="lwps_textinput" type="text" name="contactname" id="contactname" value="<?php echo $this->data['contactname']; ?>">

        <label class="lwps_label"><?php echo $this->i18n['form_country']; ?></label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_country_info']; ?></p>
        <select name="country">
            <option value=""><?php echo $this->i18n['form_pleaseselect']; ?></option>
            <?php foreach($this->countries as $country): ?>
             <option value="<?php echo $country['kuerzel3']; ?>"<?php if($this->data['country'] == $country['kuerzel3']): ?> selected="selected"<?php endif; ?>><?php echo utf8_decode($country['name_de']); ?></option>
            <?php endforeach; ?>
        </select>
        
        <label class="lwps_label"><?php echo $this->i18n['form_organisationname']; ?></label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_organisationname_info']; ?></p>
        <?php if(isset($this->errors["organisation"])): ?><p class="lwps_error"><?php echo $this->errors["organisation"]; ?></p><?php endif; ?>
        <input class="lwps_textinput" type="text" name="organisation" id="organisation" value="<?php echo $this->data['organisation']; ?>">
        
        <label class="lwps_label"><?php echo $this->i18n['form_organisationtype']; ?>:</label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_organisationtype_info']; ?></p>
        <?php echo $this->organistationtypeOptions; ?>
        <br/>
        
        <label class="lwps_label"><?php echo $this->i18n['form_email']; ?>:</label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_email_info']; ?></p>
        <?php if(isset($this->errors["email"])): ?><p class="lwps_error"><?php echo $this->errors["email"]; ?></p><?php endif; ?>
        <input class="lwps_textinput" type="text" name="email" id="email" value="<?php echo $this->data['email']; ?>">
        
        <label class="lwps_label"><?php echo $this->i18n['form_phone']; ?>:</label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_phone_info']; ?></p>
        <?php if(isset($this->errors["telephone"])): ?><p class="lwps_error"><?php echo $this->errors["telephone"]; ?></p><?php endif; ?>
        <input class="lwps_textinput" type="text" name="telephone" id="telephone" value="<?php echo $this->data['telephone']; ?>">
        
        <label class="lwps_label"><?php echo $this->i18n['form_keywords']; ?>:</label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_keywords_info']; ?></p>
        <?php if(isset($this->errors["keywords"])): ?><p class="lwps_error"><?php echo $this->errors["keywords"]; ?></p><?php endif; ?>
        <input class="lwps_textinput" type="text" name="keywords" id="keywords" value="<?php echo $this->data['keywords']; ?>">
        
        <label class="lwps_label"><?php echo $this->i18n['form_topic']; ?>:</label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_topic_info']; ?></p>
        <?php echo $this->topicOptions; ?>
        <br/>
        
        <label class="lwps_label"><?php echo $this->i18n['form_description']; ?></label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_description_info']; ?></p>
        <?php if(isset($this->errors["description"])): ?><p class="lwps_error"><?php echo $this->errors["description"]; ?></p><?php endif; ?>
        <textarea class="lwps_textarea" name="description" id="description"><?php echo $this->f($this->data['description']); ?></textarea>
        <br/> 
        
        <label class="lwps_label"><?php echo $this->i18n['form_orgadesc']; ?></label>
        <p class="lwps_infotext"><?php echo $this->i18n['form_orgadesc_info']; ?></p>
        <?php if(isset($this->errors["orgadesc"])): ?><p class="lwps_error"><?php echo $this->errors["orgadesc"]; ?></p><?php endif; ?>
        <textarea class="lwps_textarea" name="orgadesc" id="orgadesc"><?php echo $this->f($this->data['orgadesc']); ?></textarea>
        
        <?php if(!$this->isAdmin): ?>
    	<input class="lwps_button" name="submitbutton" type="submit" value="<?php echo $this->i18n['form_nextstep']; ?>" />
        <?php endif; ?>
        
        <?php if($this->isAdmin === true): ?>
    	<input class="lwps_button" name="cancel" type="button" onclick="document.location.href='<?php echo $this->backUrl; ?>';" value="<?php echo $this->i18n['form_cancel']; ?>" />&nbsp;
    	<input class="lwps_button" name="submitbutton" type="submit" value="<?php echo $this->i18n['form_save']; ?>" />
        <?php endif; ?>
    
    </form>

</div>
