<div class="lwse_form">

	<h1 class="page-title"><?php echo $this->i18n['list_headline']; ?></h1>
    <form action="<?php echo $this->actionUrl; ?>" id="filterform" method="POST">
        <input type="hidden" name="changefilter" value="1" />
        <select name="filter">
            <option value="all" <?php if ($this->filter == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showall']; ?></option>
            <option value="offer" <?php if ($this->filter == 'offer'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showoffers']; ?></option>
            <option value="search" <?php if ($this->filter == 'search'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showsearches']; ?></option>
        </select>
        <br/>
        <select name="country">
            <option value="all" <?php if ($this->country == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_allcountries']; ?></option>
            <?php foreach($this->countries as $country): ?>
             <option value="<?php echo $country['kuerzel3']; ?>"<?php if($this->country == $country['kuerzel3']): ?> selected="selected"<?php endif; ?>><?php echo utf8_decode($country['name_de']); ?></option>
            <?php endforeach; ?>
        </select>
        <br/>
        <select name="topic">
            <option value="all" <?php if ($this->topic == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_alltopics']; ?></option>
            <?php foreach($this->topics as $id => $name): ?>
             <option value="<?php echo $id; ?>"<?php if($this->topic == $id): ?> selected="selected"<?php endif; ?>><?php echo $name; ?></option>
            <?php endforeach; ?>
        </select>
        <br/>
        <select name="orgatype">
            <option value="all" <?php if ($this->orgatype == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_alltypes']; ?></option>
            <?php foreach($this->orgatypes as $id => $name): ?>
             <option value="<?php echo $id; ?>"<?php if($this->orgatype == $id): ?> selected="selected"<?php endif; ?>><?php echo $name; ?></option>
            <?php endforeach; ?>
        </select>
        <br/>
        <input type="text" size="50" name="freetext" value="<?php echo $this->freetext; ?>" />
        <input type="submit" name="search" value="<?php echo $this->i18n['list_search']; ?>" />
    </form>
    <hr/>
	<?php if(count($this->entries) == 0): ?>
    	<p><?php echo $this->i18n['list_noentriessearch']; ?></p>
    <?php endif; ?>
	<?php foreach($this->entries as $entry): ?>    
    <?php foreach($entry as $key=>$value) {       
        $entry[$key] = strip_tags($entry[$key]);
        $entry[$key] = htmlentities($entry[$key],ENT_QUOTES,'UTF-8');
    } 
    ?>
    <div class="entry">
        <h2 class="searchoroffer"><?php echo $this->i18n['list_type_'.$entry['request_type']]; ?></h2>
        <div class="thetopic"><?php echo $this->topics[$entry['topic']]; ?></div>
        <h2 class="organisation"><a href="<?php echo $this->viewUrl.'&id='.$entry['id']; ?>"><?php echo $entry['organisation']; ?></a></h2>
        <h3 class="contactname"><?php echo $entry['contactname']; ?>, <?php echo $this->formatDate($entry['created_at']); ?></h3>
        <p class="description"><?php         
        if (strlen($entry['description']) > 255) {
            $entry['description'] = substr($entry['description'],0,255).' ...';
        }
        echo $entry['description'];
         ?></p>
         <p class="description"><strong><?php echo $this->i18n['list_keywords']; ?></strong>: <?php echo $entry['keywords']; ?></p>
    </div>
    <hr/>
	<?php endforeach; ?>

</div>
