<div class="lwps_form">

	<h1 class="lwps_headline"><?php echo $this->i18n['list_headline']; ?></h1>
    
    <form action="<?php echo $this->actionUrl; ?>" id="filterform" method="POST">
        
        <input type="hidden" name="changefilter" value="1" />
        
        <div class="lwps_searchfilter">
            <select name="filter">
                <option value="all" <?php if ($this->filter == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showall']; ?></option>
                <option value="offer" <?php if ($this->filter == 'offer'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showoffers']; ?></option>
                <option value="search" <?php if ($this->filter == 'search'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showsearches']; ?></option>
            </select>
        </div>
        
        <div class="lwps_searchfilter">
            <select name="country">
                <option value="all" <?php if ($this->country == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_allcountries']; ?></option>
                <?php foreach($this->countries as $country): ?>
                 <option value="<?php echo $country['kuerzel3']; ?>"<?php if($this->country == $country['kuerzel3']): ?> selected="selected"<?php endif; ?>><?php echo utf8_decode($country['name_de']); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        
        <div class="lwps_searchfilter">
            <select name="topic">
                <option value="all" <?php if ($this->topic == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_alltopics']; ?></option>
                <?php foreach($this->topics as $id => $name): ?>
                 <option value="<?php echo $id; ?>"<?php if($this->topic == $id): ?> selected="selected"<?php endif; ?>><?php echo $name; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        
        <div class="lwps_searchfilter">
            <select name="orgatype">
                <option value="all" <?php if ($this->orgatype == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_alltypes']; ?></option>
                <?php foreach($this->orgatypes as $id => $name): ?>
                 <option value="<?php echo $id; ?>"<?php if($this->orgatype == $id): ?> selected="selected"<?php endif; ?>><?php echo $name; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        
        <input type="text" size="50" name="freetext" value="<?php echo $this->freetext; ?>" />
        <input type="submit" name="search" value="<?php echo $this->i18n['list_search']; ?>" />

    </form>
    
    <hr/>

	<?php if(count($this->entries) == 0): ?>

    	<p class="lwps_infotext"><?php echo $this->i18n['list_noentriessearch']; ?></p>

    <?php else: ?>
	
    <div class="lwps_searchresult">
	    <?php foreach($this->entries as $entry): ?>    
        
        <?php foreach($entry as $key=>$value) {       
            $entry[$key] = strip_tags($entry[$key]);
            $entry[$key] = htmlentities($entry[$key],ENT_QUOTES,'UTF-8');
        } 
        ?>
        
        <div class="lwps_entry">
            
            <div class="lwps_organisation">
                <a href="<?php echo $this->viewUrl.'&id='.$entry['id']; ?>"><?php echo $entry['organisation']; ?></a>
            </div>

            <div class="lwps_searchoroffer"><?php echo $this->i18n['list_type_'.$entry['request_type']]; ?></div>
            
            <div class="lwps_topic"><?php echo $this->topics[$entry['topic']]; ?></div>
            
            <div class="lwps_metadata">
                <span class="lwps_contact"><?php echo $entry['contactname']; ?></span>, <span class="lwps_date"><?php echo $this->formatDate($entry['created_at']); ?></span>
            </div>
            
            <p class="lwps_description"><?php         
            if (strlen($entry['description']) > 255) {
                $entry['description'] = substr($entry['description'],0,255).' ...';
            }
            echo $entry['description'];
             ?></p>
             
             <p class="lwps_keywordsarea">
                <label><?php echo $this->i18n['list_keywords']; ?>: </label><div class="lwps_keywords"><?php echo $entry['keywords']; ?></div>
             </p>
             
        </div>
        
        <hr/>
        
	    <?php endforeach; ?>
	    
	</div>

    <?php endif; ?> 
    
</div>
