<link rel="stylesheet" href="https://www.nks-umwelt.de/assets/css/lwps_bmbf.css" type="text/css" />
<div class="lwPartneringTool">

	<h1><?php echo $this->i18n['adminlist_headline']; ?></h1>


    <form action="<?php echo $this->actionUrl; ?>" id="filterform" method="POST">
        <input type="hidden" name="changefilter" value="1" />

        <div class="pcgcsuche">

            <fieldset>
                    
                <select name="filter" onchange="document.getElementById('filterform').submit();">
                    <option value="all" <?php if ($this->filter == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['adminlist_showall']; ?></option>
                    <option value="unpublished" <?php if ($this->filter == 'unpublished'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['adminlist_showunpublished']; ?></option>
                    <option value="published" <?php if ($this->filter == 'published'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['adminlist_showpublished']; ?></option>
                </select>
                <br/>

            </fieldset>

        </div>            
       
    </form>

    <?php if(count($this->entries) == 0): ?>
    <p style="margin-top:30px;"><?php echo $this->i18n['adminlist_noentriesavailable']; ?></p>
    <?php endif; ?>

    <div id="htdig">
        <ul>

            <?php foreach($this->entries as $entry): ?>

            <?php foreach($entry as $key=>$value) {
               
                $entry[$key] = strip_tags($entry[$key]);
                $entry[$key] = htmlentities($entry[$key],ENT_QUOTES,'UTF-8');
                if ($oddeven=="bgweiss") $oddeven = "bgblue"; else $oddeven="bgweiss";
                
            } 
            ?>

            <li class="<?php echo $oddeven; ?>">
                <h3>
                    <a href="<?php echo $this->editUrl; ?>&id=<?php echo $entry['id']; ?>">
                        <?php echo $entry['organisation']; ?>
                    </a>
                </h3>
                <p class="meta">
                    <strong></strong><br/>
                    <strong><?php echo $this->i18n['list_keywords']; ?></strong>: <?php echo $entry['keywords']; ?>
                </p>
                <p><?php 
                    if (strlen($entry['description']) > 255) {
                        $entry['description'] = substr($entry['description'],0,255).' ...';
                    }
                    echo $entry['description'];
                    ?>
                </p>

                <?php if($entry['published'] < 1):?>
                <p class="notpublishedyet">
                    <?php echo $this->i18n['adminlist_entryisnotpublished']; ?>
                </p>
                <?php endif; ?>

                <p class="search_url">
                    <strong><?php echo $this->i18n['adminlist_type_'.$entry['request_type']]; ?></strong>
                    - <?php echo $this->formatDate($entry['created_at']); ?>
                </p>                 

            </li>
            <?php endforeach; ?>

        </ul>
    </div>

</div>
