<link rel="stylesheet" href="https://www.nks-umwelt.de/assets/css/lwps_bmbf.css" type="text/css" />
<div class="lwPartneringTool">

	<h1><?php echo $this->i18n['list_headline']; ?></h1>

    <?php if(strlen(trim($this->introduction))>0): ?>
    <p><?php echo $this->introduction; ?></p>
    <?php endif; ?>

    <form action="<?php echo $this->actionUrl; ?>" id="filterform" method="POST">
        <input type="hidden" name="changefilter" value="1" />

        <div class="pcgcsuche">

            <fieldset>

                <legend><strong><?php echo $this->i18n['list_searchlegend']; ?></strong></legend>

                <label for="filter"><?php echo $this->i18n['list_filter']; ?>:</label><br />
                <select id="filter" name="filter" class="lwps_searchdropdown">
                    <option value="all" <?php if ($this->filter == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showall']; ?></option>
                    <option value="offer" <?php if ($this->filter == 'offer'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showoffers']; ?></option>
                    <option value="search" <?php if ($this->filter == 'search'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_showsearches']; ?></option>
                </select>
                <br/><br/>

                <label for="country"><?php echo $this->i18n['list_country']; ?>:</label><br />
                <select name="country" class="lwps_searchdropdown">
                    <option value="all" <?php if ($this->country == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_allcountries']; ?></option>
                    <?php foreach($this->countries as $country): ?>
                     <option value="<?php echo $country['kuerzel3']; ?>"<?php if($this->country == $country['kuerzel3']): ?> selected="selected"<?php endif; ?>><?php echo utf8_decode($country['name_de']); ?></option>
                    <?php endforeach; ?>
                </select>
                <br/><br/>

                <label for="topic"><?php echo $this->i18n['list_topic']; ?>:</label><br />
                <select name="topic" class="lwps_searchdropdown">
                    <option value="all" <?php if ($this->topic == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_alltopics']; ?></option>
                    <?php foreach($this->topics as $id => $name): ?>
                     <option value="<?php echo $id; ?>"<?php if($this->topic == $id): ?> selected="selected"<?php endif; ?>><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <br/><br>

                <label for="orgatype"><?php echo $this->i18n['list_orgatype']; ?>:</label><br />
                <select name="orgatype" class="lwps_searchdropdown">
                    <option value="all" <?php if ($this->orgatype == 'all'): ?>selected="selected"<?php endif; ?>><?php echo $this->i18n['list_alltypes']; ?></option>
                    <?php foreach($this->orgatypes as $id => $name): ?>
                     <option value="<?php echo $id; ?>"<?php if($this->orgatype == $id): ?> selected="selected"<?php endif; ?>><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <br/><br/>

                <label for="freetext"><?php echo $this->i18n['list_freetext']; ?>:</label><br />
                <input class="lwps_input" type="text" size="50" name="freetext" value="<?php echo $this->freetext; ?>" />
                <br/>
        
            </fieldset>

        </div>            
       
        <div id="pcgcsfsubmitarea">

            <div class="pcgcbcontrol">
                <input class="whitespacerightsmall bmbfinput_submit" type="submit" name="search" value="<?php echo $this->i18n['list_search']; ?>"></input>
            </div>

        </div>       
       
    </form>

	<?php if(count($this->entries) == 0): ?>
    	<p><?php echo $this->i18n['list_noentriessearch']; ?></p>
    <?php endif; ?>

    <div id="htdig">
        <ul>
        
	        <?php foreach($this->entries as $entry): ?>    
            <?php foreach($entry as $key=>$value) {       
                $entry[$key] = strip_tags($entry[$key]);
                $entry[$key] = htmlentities($entry[$key],ENT_QUOTES,'UTF-8');
                if ($oddeven=="bgweiss") $oddeven = "bgblue"; else $oddeven="bgweiss";
            } 
            ?>
            <li class="<?php echo $oddeven; ?>">
                <h3>
                    <a href="<?php echo $this->viewUrl.'&id='.$entry['id']; ?>">
                        <?php echo $entry['organisation']; ?>
                    </a>
                </h3>
                <p class="meta">
                    <strong><?php echo $this->i18n['list_topic']; ?></strong>: <?php echo $this->topics[$entry['topic']]; ?><br/>
                    <strong><?php echo $this->i18n['list_keywords']; ?></strong>: <?php echo $entry['keywords']; ?>
                </p>
                <p><?php         
                if (strlen($entry['description']) > 255) {
                $entry['description'] = substr($entry['description'],0,255).'...';
                }
                echo $entry['description'];
                ?></p>
                <p class="search_url">
                    <strong><?php echo $this->i18n['list_type_'.$entry['request_type']]; ?></strong>
                    - <?php echo $this->formatDate($entry['created_at']); ?>
                </p>                 
            </li>
	        <?php endforeach; ?>
        </ul>
    </div>

</div>
